format = """
$username[@](green dimmed)$hostname $directory$git_branch$git_commit$git_state$git_status$all
$jobs$battery$time($status )$cmd_duration$character
"""

[aws]
symbol = "îŒ½ "

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[character]
success_symbol = "â†’"
error_symbol = "[â†’](red)"
vicmd_symbol = "[â†“](yellow)"

[cmd_duration]
style = "purple"

[directory]
style = "purple"
truncate_to_repo = false

[conda]
symbol = "ï„Œ "

[dotnet]
style = "blue"
symbol = "î¿ "

[git_branch]
style = "yellow"
symbol = "ï˜ "

[git_commit]
style = "green"

[git_status]
style = "red dimmed"

[golang]
style = "cyan"
symbol = "î˜§ "

[hg_branch]
symbol = "ï˜ "

[hostname]
format = "[$hostname]($style)"
style = "green"
ssh_only = false

[java]
symbol = "î‰– "

[line_break]
disabled = true

[memory_usage]
symbol = "ï¡š "

[nodejs]
style = "green"
symbol = "î‰ "

[package]
style = "orange"
symbol = "ï£– "

[php]
style = "red"
symbol = "î˜ˆ "

[python]
style = "yellow"
symbol = "î˜† "

[ruby]
style = "red"
symbol = "îˆ¾ "

[rust]
style = "red"
symbol = "ï€“ "

[status]
disabled = false
symbol                = "âœ– "
success_symbol        = "âœ”ï¸"
not_executable_symbol = "ğŸš« "
not_found_symbol      = "ğŸ”"
sigint_symbol         = "ğŸ§± "
signal_symbol         = "âš¡"
format = "[$symbol($common_meaning)(SIG$signal_name)($maybe_int)]($style)"
pipestatus_separator = " | "
pipestatus_format = "\\[ $pipestatus \\] â†’ [$symbol($common_meaning)(SIG$signal_name)($maybe_int)]($style)"
map_symbol = true
pipestatus = true

[time]
disabled = false
format = "[$time]($style) "
style = "yellow dimmed"
time_format = "%H:%M"

[username]
format = "[$user]($style)"
style_user = "green"
show_always = true
